### ISSUE TITLE
Failed to start the wazuh-indexer service

### ISSUE THREAD

**Issue by MikeKall** [wazuh/wazuh-indexer#439]
Hello,
I am not sure if I should post this here but I can't find any safe solutions unfortunately for my issue. 

I updated the wazuh-indexer from 4.7 to 4.9. When I tried to start the wazuh-indexer service it I got timed-out. The error from the logs is the following:
```
[2024-10-02T15:50:09,613][ERROR][o.o.b.Bootstrap          ] [wazuhsvcindexer01] Exception
java.lang.IllegalStateException: failed to load plugin repository-azure due to jar hell
        at org.opensearch.plugins.PluginsService.checkBundleJarHell(PluginsService.java:692) ~[opensearch-2.13.0.jar:2.13.0]
        at org.opensearch.plugins.PluginsService.loadBundles(PluginsService.java:542) ~[opensearch-2.13.0.jar:2.13.0]
        at org.opensearch.plugins.PluginsService.<init>(PluginsService.java:196) ~[opensearch-2.13.0.jar:2.13.0]
        at org.opensearch.node.Node.<init>(Node.java:490) ~[opensearch-2.13.0.jar:2.13.0]
        at org.opensearch.node.Node.<init>(Node.java:417) ~[opensearch-2.13.0.jar:2.13.0]
        at org.opensearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:242) ~[opensearch-2.13.0.jar:2.13.0]
        at org.opensearch.bootstrap.Bootstrap.setup(Bootstrap.java:242) ~[opensearch-2.13.0.jar:2.13.0]
        at org.opensearch.bootstrap.Bootstrap.init(Bootstrap.java:404) [opensearch-2.13.0.jar:2.13.0]
        at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:181) [opensearch-2.13.0.jar:2.13.0]
        at org.opensearch.bootstrap.OpenSearch.execute(OpenSearch.java:172) [opensearch-2.13.0.jar:2.13.0]
        at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:104) [opensearch-2.13.0.jar:2.13.0]
        at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138) [opensearch-cli-2.13.0.jar:2.13.0]
        at org.opensearch.cli.Command.main(Command.java:101) [opensearch-cli-2.13.0.jar:2.13.0]
        at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:138) [opensearch-2.13.0.jar:2.13.0] 1640L, 220389B
        at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:104) [opensearch-2.13.0.jar:2.13.0]
Caused by: java.lang.IllegalStateException: jar hell!
class: reactor.adapter.JdkFlowAdapter$1
jar1: /usr/share/wazuh-indexer/plugins/repository-azure/reactor-core-3.4.18.jar
jar2: /usr/share/wazuh-indexer/lib/reactor-core-3.5.15.jar
        at org.opensearch.bootstrap.JarHell.checkClass(JarHell.java:316) ~[opensearch-common-2.13.0.jar:2.13.0]
        at org.opensearch.bootstrap.JarHell.checkJarHell(JarHell.java:215) ~[opensearch-common-2.13.0.jar:2.13.0]
        at org.opensearch.plugins.PluginsService.checkBundleJarHell(PluginsService.java:690) ~[opensearch-2.13.0.jar:2.13.0]
        ... 14 more
```

I see that there are two jars that they conflict (reactor-core-3.4.18.jar and reactor-core-3.5.15.jar).
If this is the problem, should I remove one of the two and if so, how can I safely do it without causing a mess? 

**Host/Environment (please complete the following information):**
 - OS: RedHat
 - VERSION="9.4 (Plow)"

**Comment by MikeKall** [comment]
After a little bit of digging I re-installed the `repository-azure` plugin and it seems like the service is running with no errors, yet.
