### ISSUE TITLE
Integrations maintenance request

### ISSUE THREAD

**Issue by mcasas993** [wazuh/wazuh-indexer#445]
## Description

The Wazuh Indexer team is responsible for the maintenance of the third-party integrations hosted in the wazuh/wazuh-indexer repository. We must ensure these integrations work under new releases of the third-party software (Splunk, OpenSearch, Logstash) and our own.

For that, we need to:

-   [x] Update our testing environments to verify the integrations work under new versions.

## Issues

- _List here the detected issues_

**Comment by mcasas993** [comment]
##Opensearch Integration
We test seven dashboards.

**wazuh-vulnerabilities-v1.0**
![image](https://github.com/user-attachments/assets/442a6ed8-311e-425d-b136-372df869c33b)

**wazuh-security-events-v1.0**
![image](https://github.com/user-attachments/assets/882a8e21-eba8-42e6-93e1-abd395f17387)

**wazuh-pci-dss-v1.0**
![image](https://github.com/user-attachments/assets/b34381b6-c92f-4c3c-8147-595791501918)

**wazuh-malware-detection-v1.0**
![image](https://github.com/user-attachments/assets/0a1dcd22-f346-430b-b896-9b7d7cd4efea)

**wazuh-incident-response-v1.0**
![image](https://github.com/user-attachments/assets/92ccc751-dfae-4a55-8b9d-dd1bc3966c62)

**wazuh-amazon-aws-v1.0**
![image](https://github.com/user-attachments/assets/cb6bb7ab-b729-43d6-9adf-74126ba60ae5)

**Comment by mcasas993** [comment]
When I go to Discover section to search data for the Docker Dashboard, I found this error:

```
illegal_argument_exception
Field [data.osquery.calendarTime] of type [keyword] does not support custom formats
Error: Bad Request
    at fetch_Fetch.fetchResponse (https://localhost:5602/7969/bundles/core/core.entry.js:15:392113)
    at async interceptResponse (https://localhost:5602/7969/bundles/core/core.entry.js:15:386867)
    at async https://localhost:5602/7969/bundles/core/core.entry.js:15:389834
```

**Comment by mcasas993** [comment]
## Elasticsearch Integration
We test seven dashboards.

**wazuh-vulnerabilities-v1.0**
![image](https://github.com/user-attachments/assets/7c57e212-62a2-4252-bd3a-c7b1149a3fc3)

**wazuh-security-events-v1.0**
![image](https://github.com/user-attachments/assets/544735c5-4595-48a5-ace0-3f1076310985)

**wazuh-pci-dss-v1.0**
![image](https://github.com/user-attachments/assets/4bbd8a21-b715-4b71-a699-b1ed01df917d)

**wazuh-malware-detection-v1.0**
![image](https://github.com/user-attachments/assets/b4494d0d-ae4f-4651-8fce-a1a068dd80bf)

**wazuh-incident-response-v1.0**
![image](https://github.com/user-attachments/assets/4235d216-0826-4406-96dc-1b4719d7da65)

**wazuh-amazon-aws-v1.0**

**wazuh-docker-listener-v1.0**

**Comment by mcasas993** [comment]
## Splunk Integration
We test seven dashboards.

**wazuh-vulnerabilities-v1.0**
![image](https://github.com/user-attachments/assets/2af97ef4-790d-4837-891a-4418cc71b0d0)

**wazuh-security-events-v1.0**
![image](https://github.com/user-attachments/assets/592bc384-41d5-43dd-ad9a-3e4f59472433)

**wazuh-pci-dss-v1.0**
![image](https://github.com/user-attachments/assets/09d1612c-aa60-4d51-9de6-8adbf4d3898c)

**wazuh-malware-detection-v1.0**
![image](https://github.com/user-attachments/assets/e1c8e2fe-f3ac-41e5-8711-e37c3a07f2af)

**wazuh-incident-response-v1.0**
![image](https://github.com/user-attachments/assets/dec8a57b-eb25-4d2e-86ac-e2752620bdbb)

**wazuh-amazon-aws-v1.0**
![image](https://github.com/user-attachments/assets/e02e440f-d439-4464-81fc-72ecac70451b)

**wazuh-docker-listener-v1.0**
![image](https://github.com/user-attachments/assets/0caf73e2-448a-468a-bce9-0376c4d66adb)
