### ISSUE TITLE
[BUG] indexer broken after adding username and password to the keystore for notifications

### ISSUE THREAD

**Issue by Orgoth** [wazuh/wazuh-indexer#552]
**Describe the bug**
Tried to set up notifications as recommended by the dashboard!
But after adding username and passwort to the opensearch keystore, the whole indexer is broken.

**To Reproduce**
1. Go to /app/notifications-dashboards#/create-smtp-sender
2. create a new sender uniquename "wazu_01", smtp domain, email, port 465
3. do not follow the learn more link, since it is outdated "https://opensearch.org/docs/monitoring-plugins/alerting/monitors/#authenticate-sender-account" and redirects to "https://opensearch.org/docs/latest/observing-your-data/alerting/monitors/" which does not help at all.
4. therefore i followed this link: https://opensearch.org/docs/latest/observing-your-data/notifications/index/#authenticate-sender-account
5. added user and password to the keystore
```
/usr/share/wazuh-indexer/bin/opensearch-keystore add opensearch.notifications.core.email.wazu_01.username
/usr/share/wazuh-indexer/bin/opensearch-keystore add opensearch.notifications.core.email.wazu_01.password
```
6. restarted indexer

**Expected behavior**
Indexer should have started without any problems, since I have only added data for wazu_01 and nothing else!

**Errors**
```
Nov 15 07:22:31 wazuh.somedomain.de systemd-entrypoint[164660]: Exception in thread "main" java.nio.file.AccessDeniedException: /etc/wazuh-indexer/opensearch.keystore
Nov 15 07:22:31 wazuh.somedomain.de systemd-entrypoint[164660]:         at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
Nov 15 07:22:31 wazuh.somedomain.de systemd-entrypoint[164660]:         at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
Nov 15 07:22:31 wazuh.somedomain.de systemd-entrypoint[164660]:         at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
Nov 15 07:22:31 wazuh.somedomain.de systemd-entrypoint[164660]:         at java.base/sun.nio.fs.UnixFileSystemProvider.newFileChannel(UnixFileSystemProvider.java:224)
Nov 15 07:22:31 wazuh.somedomain.de systemd-entrypoint[164660]:         at java.base/java.nio.channels.FileChannel.open(FileChannel.java:309)
Nov 15 07:22:31 wazuh.somedomain.de systemd-entrypoint[164660]:         at java.base/java.nio.channels.FileChannel.open(FileChannel.java:369)
Nov 15 07:22:31 wazuh.somedomain.de systemd-entrypoint[164660]:         at org.apache.lucene.store.NIOFSDirectory.openInput(NIOFSDirectory.java:78)
Nov 15 07:22:31 wazuh.somedomain.de systemd-entrypoint[164660]:         at org.apache.lucene.store.Directory.openChecksumInput(Directory.java:156)
Nov 15 07:22:31 wazuh.somedomain.de systemd-entrypoint[164660]:         at org.apache.lucene.backward_codecs.store.EndiannessReverserUtil.openChecksumInput(EndiannessReverserUtil.java:48)
Nov 15 07:22:31 wazuh.somedomain.de systemd-entrypoint[164660]:         at org.opensearch.common.settings.KeyStoreWrapper.load(KeyStoreWrapper.java:248)
Nov 15 07:22:31 wazuh.somedomain.de systemd-entrypoint[164660]:         at org.opensearch.common.settings.KeyStoreWrapper.load(KeyStoreWrapper.java:232)
Nov 15 07:22:31 wazuh.somedomain.de systemd-entrypoint[164660]:         at org.opensearch.common.settings.HasPasswordKeyStoreCommand.execute(HasPasswordKeyStoreCommand.java:61)
Nov 15 07:22:31 wazuh.somedomain.de systemd-entrypoint[164660]:         at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:104)
Nov 15 07:22:31 wazuh.somedomain.de systemd-entrypoint[164660]:         at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138)
Nov 15 07:22:31 wazuh.somedomain.de systemd-entrypoint[164660]:         at org.opensearch.cli.MultiCommand.execute(MultiCommand.java:104)
Nov 15 07:22:31 wazuh.somedomain.de systemd-entrypoint[164660]:         at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138)
Nov 15 07:22:31 wazuh.somedomain.de systemd-entrypoint[164660]:         at org.opensearch.cli.Command.main(Command.java:101)
Nov 15 07:22:31 wazuh.somedomain.de systemd-entrypoint[164660]:         at org.opensearch.common.settings.KeyStoreCli.main(KeyStoreCli.java:56)
Nov 15 07:22:32 wazuh.somedomain.de systemd-entrypoint[164604]: WARNING: A terminally deprecated method in java.lang.System has been called
Nov 15 07:22:32 wazuh.somedomain.de systemd-entrypoint[164604]: WARNING: System::setSecurityManager has been called by org.opensearch.bootstrap.OpenSearch (file:/usr/share/wazuh-indexer/lib/opensearch-2.13.0.jar)
Nov 15 07:22:32 wazuh.somedomain.de systemd-entrypoint[164604]: WARNING: Please consider reporting this to the maintainers of org.opensearch.bootstrap.OpenSearch
Nov 15 07:22:32 wazuh.somedomain.de systemd-entrypoint[164604]: WARNING: System::setSecurityManager will be removed in a future release
Nov 15 07:22:32 wazuh.somedomain.de systemd-entrypoint[164604]: Exception in thread "main" org.opensearch.bootstrap.BootstrapException: java.nio.file.AccessDeniedException: /etc/wazuh-indexer/opensearch.keystore
Nov 15 07:22:32 wazuh.somedomain.de systemd-entrypoint[164604]: Likely root cause: java.nio.file.AccessDeniedException: /etc/wazuh-indexer/opensearch.keystore
Nov 15 07:22:32 wazuh.somedomain.de systemd-entrypoint[164604]:         at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
Nov 15 07:22:32 wazuh.somedomain.de systemd-entrypoint[164604]:         at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
Nov 15 07:22:32 wazuh.somedomain.de systemd-entrypoint[164604]:         at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
Nov 15 07:22:32 wazuh.somedomain.de systemd-entrypoint[164604]:         at java.base/sun.nio.fs.UnixFileSystemProvider.newFileChannel(UnixFileSystemProvider.java:224)
Nov 15 07:22:32 wazuh.somedomain.de systemd-entrypoint[164604]:         at java.base/java.nio.channels.FileChannel.open(FileChannel.java:309)
Nov 15 07:22:32 wazuh.somedomain.de systemd-entrypoint[164604]:         at java.base/java.nio.channels.FileChannel.open(FileChannel.java:369)
Nov 15 07:22:32 wazuh.somedomain.de systemd-entrypoint[164604]:         at org.apache.lucene.store.NIOFSDirectory.openInput(NIOFSDirectory.java:78)
Nov 15 07:22:32 wazuh.somedomain.de systemd-entrypoint[164604]:         at org.apache.lucene.store.Directory.openChecksumInput(Directory.java:156)
Nov 15 07:22:32 wazuh.somedomain.de systemd-entrypoint[164604]:         at org.apache.lucene.backward_codecs.store.EndiannessReverserUtil.openChecksumInput(EndiannessReverserUtil.java:48)
Nov 15 07:22:32 wazuh.somedomain.de systemd-entrypoint[164604]:         at org.opensearch.common.settings.KeyStoreWrapper.load(KeyStoreWrapper.java:248)
Nov 15 07:22:32 wazuh.somedomain.de systemd-entrypoint[164604]:         at org.opensearch.common.settings.KeyStoreWrapper.load(KeyStoreWrapper.java:232)
Nov 15 07:22:32 wazuh.somedomain.de systemd-entrypoint[164604]:         at org.opensearch.bootstrap.Bootstrap.loadSecureSettings(Bootstrap.java:257)
Nov 15 07:22:32 wazuh.somedomain.de systemd-entrypoint[164604]:         at org.opensearch.bootstrap.Bootstrap.init(Bootstrap.java:368)
Nov 15 07:22:32 wazuh.somedomain.de systemd-entrypoint[164604]:         at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:181)
Nov 15 07:22:32 wazuh.somedomain.de systemd-entrypoint[164604]:         at org.opensearch.bootstrap.OpenSearch.execute(OpenSearch.java:172)
Nov 15 07:22:32 wazuh.somedomain.de systemd-entrypoint[164604]:         at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:104)
Nov 15 07:22:32 wazuh.somedomain.de systemd-entrypoint[164604]:         at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138)
Nov 15 07:22:32 wazuh.somedomain.de systemd-entrypoint[164604]:         at org.opensearch.cli.Command.main(Command.java:101)
Nov 15 07:22:32 wazuh.somedomain.de systemd-entrypoint[164604]:         at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:138)
Nov 15 07:22:32 wazuh.somedomain.de systemd-entrypoint[164604]:         at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:104)
```

**Host/Environment (please complete the following information):**
 - OS: Ubuntu 24.04 LTS
 - Wazuh 4.9.2

**Additional context**

I have a postfix smarthost running which works completely fine for all CLI related notifications.
For example: echo "Test mail from postfix" | mail -s "Test Postfix" -r "<CONFIGURED_EMAIL>" <RECEIVER_EMAIL>
Works just fine.
But the Dashboard Notifications are using a completely different notifications service then the wazu manager.

**Comment by AlexRuiz7** [comment]
Hello @Orgoth 

You can revert the situation by removing the keystore. Be sure to make a **backup** before doing so:

```console
sudo rm /etc/wazuh-indexer/opensearch-keystore
```

I'll try to reproduce the issue.

**Comment by AlexRuiz7** [comment]
I was able to reproduce the issue. You need one more step before restarting the indexer, which is to ensure the keystore belongs to the `wazuh-indexer` user so it can be accessed.

If you invoke `/usr/share/wazuh-indexer/bin/opensearch-keystore` with any other user than `wazuh-indexer` and the keystore is to be created, it's created for the user and group that invoked the command.

Below, the steps used to reproduce the issue using the `root` user, and later fixed by changing the owner of the keystore's file.

```
[root@alma9 vagrant]# cd /usr/share/wazuh-indexer/
[root@alma9 wazuh-indexer]# /usr/share/wazuh-indexer/bin/opensearch-keystore add opensearch.notifications.core.email.wazuh_01.username
Enter value for opensearch.notifications.core.email.wazuh_01.username: 
[root@alma9 wazuh-indexer]# /usr/share/wazuh-indexer/bin/opensearch-keystore add opensearch.notifications.core.email.wazuh_01.password
Enter value for opensearch.notifications.core.email.wazuh_01.password: 
[root@alma9 wazuh-indexer]# systemctl restart wazuh-indexer
Job for wazuh-indexer.service failed because the control process exited with error code.
See "systemctl status wazuh-indexer.service" and "journalctl -xeu wazuh-indexer.service" for details.
[root@alma9 wazuh-indexer]# systemctl status wazuh-indexer
× wazuh-indexer.service - wazuh-indexer
     Loaded: loaded (/usr/lib/systemd/system/wazuh-indexer.service; enabled; preset: disabled)
     Active: failed (Result: exit-code) since Mon 2024-11-25 13:21:34 UTC; 12s ago
   Duration: 1h 7min 57.891s
       Docs: https://documentation.wazuh.com
    Process: 11829 ExecStart=/usr/share/wazuh-indexer/bin/systemd-entrypoint -p ${PID_DIR}/wazuh-indexer.pid --quiet (code=exited, status=1/FAILURE)
   Main PID: 11829 (code=exited, status=1/FAILURE)
        CPU: 1.625s

Nov 25 13:21:34 alma9.localdomain systemd-entrypoint[11829]:         at org.opensearch.bootstrap.OpenSearch.execute(OpenSearch.java:172)
Nov 25 13:21:34 alma9.localdomain systemd-entrypoint[11829]:         at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:104)
Nov 25 13:21:34 alma9.localdomain systemd-entrypoint[11829]:         at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138)
Nov 25 13:21:34 alma9.localdomain systemd-entrypoint[11829]:         at org.opensearch.cli.Command.main(Command.java:101)
Nov 25 13:21:34 alma9.localdomain systemd-entrypoint[11829]:         at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:138)
Nov 25 13:21:34 alma9.localdomain systemd-entrypoint[11829]:         at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:104)
Nov 25 13:21:34 alma9.localdomain systemd[1]: wazuh-indexer.service: Main process exited, code=exited, status=1/FAILURE
Nov 25 13:21:34 alma9.localdomain systemd[1]: wazuh-indexer.service: Failed with result 'exit-code'.
Nov 25 13:21:34 alma9.localdomain systemd[1]: Failed to start wazuh-indexer.
Nov 25 13:21:34 alma9.localdomain systemd[1]: wazuh-indexer.service: Consumed 1.625s CPU time.
[root@alma9 wazuh-indexer]# journalctl -xeu wazuh-indexer --no-pager
Nov 25 12:13:31 alma9.localdomain systemd[1]: Starting wazuh-indexer...
░░ Subject: A start job for unit wazuh-indexer.service has begun execution
░░ Defined-By: systemd
░░ Support: https://access.redhat.com/support
░░ 
░░ A start job for unit wazuh-indexer.service has begun execution.
░░ 
░░ The job identifier is 1095.
Nov 25 12:13:31 alma9.localdomain systemd-entrypoint[4199]: WARNING: A terminally deprecated method in java.lang.System has been called
Nov 25 12:13:31 alma9.localdomain systemd-entrypoint[4199]: WARNING: System::setSecurityManager has been called by org.opensearch.bootstrap.OpenSearch (file:/usr/share/wazuh-indexer/lib/opensearch-2.13.0.jar)
Nov 25 12:13:31 alma9.localdomain systemd-entrypoint[4199]: WARNING: Please consider reporting this to the maintainers of org.opensearch.bootstrap.OpenSearch
Nov 25 12:13:31 alma9.localdomain systemd-entrypoint[4199]: WARNING: System::setSecurityManager will be removed in a future release
Nov 25 12:13:31 alma9.localdomain systemd-entrypoint[4199]: Nov 25, 2024 12:13:31 PM sun.util.locale.provider.LocaleProviderAdapter <clinit>
Nov 25 12:13:31 alma9.localdomain systemd-entrypoint[4199]: WARNING: COMPAT locale provider will be removed in a future release
Nov 25 12:13:32 alma9.localdomain systemd-entrypoint[4199]: WARNING: A terminally deprecated method in java.lang.System has been called
Nov 25 12:13:32 alma9.localdomain systemd-entrypoint[4199]: WARNING: System::setSecurityManager has been called by org.opensearch.bootstrap.Security (file:/usr/share/wazuh-indexer/lib/opensearch-2.13.0.jar)
Nov 25 12:13:32 alma9.localdomain systemd-entrypoint[4199]: WARNING: Please consider reporting this to the maintainers of org.opensearch.bootstrap.Security
Nov 25 12:13:32 alma9.localdomain systemd-entrypoint[4199]: WARNING: System::setSecurityManager will be removed in a future release
Nov 25 12:13:35 alma9.localdomain systemd[1]: Started wazuh-indexer.
░░ Subject: A start job for unit wazuh-indexer.service has finished successfully
░░ Defined-By: systemd
░░ Support: https://access.redhat.com/support
░░ 
░░ A start job for unit wazuh-indexer.service has finished successfully.
░░ 
░░ The job identifier is 1095.
Nov 25 13:21:33 alma9.localdomain systemd[1]: Stopping wazuh-indexer...
░░ Subject: A stop job for unit wazuh-indexer.service has begun execution
░░ Defined-By: systemd
░░ Support: https://access.redhat.com/support
░░ 
░░ A stop job for unit wazuh-indexer.service has begun execution.
░░ 
░░ The job identifier is 2970.
Nov 25 13:21:33 alma9.localdomain systemd[1]: wazuh-indexer.service: Deactivated successfully.
░░ Subject: Unit succeeded
░░ Defined-By: systemd
░░ Support: https://access.redhat.com/support
░░ 
░░ The unit wazuh-indexer.service has successfully entered the 'dead' state.
Nov 25 13:21:33 alma9.localdomain systemd[1]: Stopped wazuh-indexer.
░░ Subject: A stop job for unit wazuh-indexer.service has finished
░░ Defined-By: systemd
░░ Support: https://access.redhat.com/support
░░ 
░░ A stop job for unit wazuh-indexer.service has finished.
░░ 
░░ The job identifier is 2970 and the job result is done.
Nov 25 13:21:33 alma9.localdomain systemd[1]: wazuh-indexer.service: Consumed 1min 7.696s CPU time.
░░ Subject: Resources consumed by unit runtime
░░ Defined-By: systemd
░░ Support: https://access.redhat.com/support
░░ 
░░ The unit wazuh-indexer.service completed and consumed the indicated resources.
Nov 25 13:21:33 alma9.localdomain systemd[1]: Starting wazuh-indexer...
░░ Subject: A start job for unit wazuh-indexer.service has begun execution
░░ Defined-By: systemd
░░ Support: https://access.redhat.com/support
░░ 
░░ A start job for unit wazuh-indexer.service has begun execution.
░░ 
░░ The job identifier is 2970.
Nov 25 13:21:34 alma9.localdomain systemd-entrypoint[11872]: Exception in thread "main" java.nio.file.AccessDeniedException: /etc/wazuh-indexer/opensearch.keystore
Nov 25 13:21:34 alma9.localdomain systemd-entrypoint[11872]:         at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
Nov 25 13:21:34 alma9.localdomain systemd-entrypoint[11872]:         at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
Nov 25 13:21:34 alma9.localdomain systemd-entrypoint[11872]:         at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
Nov 25 13:21:34 alma9.localdomain systemd-entrypoint[11872]:         at java.base/sun.nio.fs.UnixFileSystemProvider.newFileChannel(UnixFileSystemProvider.java:224)
Nov 25 13:21:34 alma9.localdomain systemd-entrypoint[11872]:         at java.base/java.nio.channels.FileChannel.open(FileChannel.java:309)
Nov 25 13:21:34 alma9.localdomain systemd-entrypoint[11872]:         at java.base/java.nio.channels.FileChannel.open(FileChannel.java:369)
Nov 25 13:21:34 alma9.localdomain systemd-entrypoint[11872]:         at org.apache.lucene.store.NIOFSDirectory.openInput(NIOFSDirectory.java:78)
Nov 25 13:21:34 alma9.localdomain systemd-entrypoint[11872]:         at org.apache.lucene.store.Directory.openChecksumInput(Directory.java:156)
Nov 25 13:21:34 alma9.localdomain systemd-entrypoint[11872]:         at org.apache.lucene.backward_codecs.store.EndiannessReverserUtil.openChecksumInput(EndiannessReverserUtil.java:48)
Nov 25 13:21:34 alma9.localdomain systemd-entrypoint[11872]:         at org.opensearch.common.settings.KeyStoreWrapper.load(KeyStoreWrapper.java:248)
Nov 25 13:21:34 alma9.localdomain systemd-entrypoint[11872]:         at org.opensearch.common.settings.KeyStoreWrapper.load(KeyStoreWrapper.java:232)
Nov 25 13:21:34 alma9.localdomain systemd-entrypoint[11872]:         at org.opensearch.common.settings.HasPasswordKeyStoreCommand.execute(HasPasswordKeyStoreCommand.java:61)
Nov 25 13:21:34 alma9.localdomain systemd-entrypoint[11872]:         at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:104)
Nov 25 13:21:34 alma9.localdomain systemd-entrypoint[11872]:         at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138)
Nov 25 13:21:34 alma9.localdomain systemd-entrypoint[11872]:         at org.opensearch.cli.MultiCommand.execute(MultiCommand.java:104)
Nov 25 13:21:34 alma9.localdomain systemd-entrypoint[11872]:         at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138)
Nov 25 13:21:34 alma9.localdomain systemd-entrypoint[11872]:         at org.opensearch.cli.Command.main(Command.java:101)
Nov 25 13:21:34 alma9.localdomain systemd-entrypoint[11872]:         at org.opensearch.common.settings.KeyStoreCli.main(KeyStoreCli.java:56)
Nov 25 13:21:34 alma9.localdomain systemd-entrypoint[11829]: WARNING: A terminally deprecated method in java.lang.System has been called
Nov 25 13:21:34 alma9.localdomain systemd-entrypoint[11829]: WARNING: System::setSecurityManager has been called by org.opensearch.bootstrap.OpenSearch (file:/usr/share/wazuh-indexer/lib/opensearch-2.13.0.jar)
Nov 25 13:21:34 alma9.localdomain systemd-entrypoint[11829]: WARNING: Please consider reporting this to the maintainers of org.opensearch.bootstrap.OpenSearch
Nov 25 13:21:34 alma9.localdomain systemd-entrypoint[11829]: WARNING: System::setSecurityManager will be removed in a future release
Nov 25 13:21:34 alma9.localdomain systemd-entrypoint[11829]: Exception in thread "main" org.opensearch.bootstrap.BootstrapException: java.nio.file.AccessDeniedException: /etc/wazuh-indexer/opensearch.keystore
Nov 25 13:21:34 alma9.localdomain systemd-entrypoint[11829]: Likely root cause: java.nio.file.AccessDeniedException: /etc/wazuh-indexer/opensearch.keystore
Nov 25 13:21:34 alma9.localdomain systemd-entrypoint[11829]:         at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:90)
Nov 25 13:21:34 alma9.localdomain systemd-entrypoint[11829]:         at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
Nov 25 13:21:34 alma9.localdomain systemd-entrypoint[11829]:         at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
Nov 25 13:21:34 alma9.localdomain systemd-entrypoint[11829]:         at java.base/sun.nio.fs.UnixFileSystemProvider.newFileChannel(UnixFileSystemProvider.java:224)
Nov 25 13:21:34 alma9.localdomain systemd-entrypoint[11829]:         at java.base/java.nio.channels.FileChannel.open(FileChannel.java:309)
Nov 25 13:21:34 alma9.localdomain systemd-entrypoint[11829]:         at java.base/java.nio.channels.FileChannel.open(FileChannel.java:369)
Nov 25 13:21:34 alma9.localdomain systemd-entrypoint[11829]:         at org.apache.lucene.store.NIOFSDirectory.openInput(NIOFSDirectory.java:78)
Nov 25 13:21:34 alma9.localdomain systemd-entrypoint[11829]:         at org.apache.lucene.store.Directory.openChecksumInput(Directory.java:156)
Nov 25 13:21:34 alma9.localdomain systemd-entrypoint[11829]:         at org.apache.lucene.backward_codecs.store.EndiannessReverserUtil.openChecksumInput(EndiannessReverserUtil.java:48)
Nov 25 13:21:34 alma9.localdomain systemd-entrypoint[11829]:         at org.opensearch.common.settings.KeyStoreWrapper.load(KeyStoreWrapper.java:248)
Nov 25 13:21:34 alma9.localdomain systemd-entrypoint[11829]:         at org.opensearch.common.settings.KeyStoreWrapper.load(KeyStoreWrapper.java:232)
Nov 25 13:21:34 alma9.localdomain systemd-entrypoint[11829]:         at org.opensearch.bootstrap.Bootstrap.loadSecureSettings(Bootstrap.java:257)
Nov 25 13:21:34 alma9.localdomain systemd-entrypoint[11829]:         at org.opensearch.bootstrap.Bootstrap.init(Bootstrap.java:368)
Nov 25 13:21:34 alma9.localdomain systemd-entrypoint[11829]:         at org.opensearch.bootstrap.OpenSearch.init(OpenSearch.java:181)
Nov 25 13:21:34 alma9.localdomain systemd-entrypoint[11829]:         at org.opensearch.bootstrap.OpenSearch.execute(OpenSearch.java:172)
Nov 25 13:21:34 alma9.localdomain systemd-entrypoint[11829]:         at org.opensearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:104)
Nov 25 13:21:34 alma9.localdomain systemd-entrypoint[11829]:         at org.opensearch.cli.Command.mainWithoutErrorHandling(Command.java:138)
Nov 25 13:21:34 alma9.localdomain systemd-entrypoint[11829]:         at org.opensearch.cli.Command.main(Command.java:101)
Nov 25 13:21:34 alma9.localdomain systemd-entrypoint[11829]:         at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:138)
Nov 25 13:21:34 alma9.localdomain systemd-entrypoint[11829]:         at org.opensearch.bootstrap.OpenSearch.main(OpenSearch.java:104)
Nov 25 13:21:34 alma9.localdomain systemd[1]: wazuh-indexer.service: Main process exited, code=exited, status=1/FAILURE
░░ Subject: Unit process exited
░░ Defined-By: systemd
░░ Support: https://access.redhat.com/support
░░ 
░░ An ExecStart= process belonging to unit wazuh-indexer.service has exited.
░░ 
░░ The process' exit code is 'exited' and its exit status is 1.
Nov 25 13:21:34 alma9.localdomain systemd[1]: wazuh-indexer.service: Failed with result 'exit-code'.
░░ Subject: Unit failed
░░ Defined-By: systemd
░░ Support: https://access.redhat.com/support
░░ 
░░ The unit wazuh-indexer.service has entered the 'failed' state with result 'exit-code'.
Nov 25 13:21:34 alma9.localdomain systemd[1]: Failed to start wazuh-indexer.
░░ Subject: A start job for unit wazuh-indexer.service has failed
░░ Defined-By: systemd
░░ Support: https://access.redhat.com/support
░░ 
░░ A start job for unit wazuh-indexer.service has finished with a failure.
░░ 
░░ The job identifier is 2970 and the job result is failed.
Nov 25 13:21:34 alma9.localdomain systemd[1]: wazuh-indexer.service: Consumed 1.625s CPU time.
░░ Subject: Resources consumed by unit runtime
░░ Defined-By: systemd
░░ Support: https://access.redhat.com/support
░░ 
░░ The unit wazuh-indexer.service completed and consumed the indicated resources.      
[root@alma9 wazuh-indexer]# ls -l /etc/wazuh-indexer/
total 40
dr-x------. 2 wazuh-indexer wazuh-indexer   117 Nov 25 12:13 certs
drwxr-x---. 2 wazuh-indexer wazuh-indexer    52 Nov 25 12:14 internalusers-backup
-rw-rw----. 1 wazuh-indexer wazuh-indexer  3068 Nov 25 12:13 jvm.options
drwxr-x---. 2 wazuh-indexer wazuh-indexer     6 Oct 28 15:35 jvm.options.d
-rw-rw----. 1 wazuh-indexer wazuh-indexer 17919 Oct 28 15:35 log4j2.properties
-rw-rw----. 1 root          root            322 Nov 25 13:21 opensearch.keystore
drwxr-x---. 2 wazuh-indexer wazuh-indexer    31 Nov 25 12:13 opensearch-notifications
drwxr-x---. 2 wazuh-indexer wazuh-indexer    36 Nov 25 12:13 opensearch-notifications-core
drwxr-x---. 2 wazuh-indexer wazuh-indexer    31 Nov 25 12:13 opensearch-observability
drwxr-x---. 2 wazuh-indexer wazuh-indexer  4096 Nov 25 12:13 opensearch-performance-analyzer
drwxr-x---. 2 wazuh-indexer wazuh-indexer    35 Nov 25 12:13 opensearch-reports-scheduler
drwxr-x---. 2 wazuh-indexer wazuh-indexer  4096 Nov 25 12:13 opensearch-security
-rw-rw----. 1 wazuh-indexer wazuh-indexer  2152 Nov 25 12:13 opensearch.yml
[root@alma9 wazuh-indexer]# chown wazuh-indexer:wazuh-indexer /etc/wazuh-indexer/opensearch.keystore
[root@alma9 wazuh-indexer]# systemctl restart wazuh-indexer
[root@alma9 wazuh-indexer]# systemctl status wazuh-indexer
● wazuh-indexer.service - wazuh-indexer
     Loaded: loaded (/usr/lib/systemd/system/wazuh-indexer.service; enabled; preset: disabled)
     Active: active (running) since Mon 2024-11-25 13:23:46 UTC; 6s ago
       Docs: https://documentation.wazuh.com
   Main PID: 12016 (java)
      Tasks: 89 (limit: 24731)
     Memory: 1.4G
        CPU: 14.388s
     CGroup: /system.slice/wazuh-indexer.service
             └─12016 /usr/share/wazuh-indexer/jdk/bin/java -Xshare:auto -Dopensearch.networkaddress.cache.ttl=60 -Dopensearch.networkaddress.cache.negative.ttl=10>

Nov 25 13:23:41 alma9.localdomain systemd-entrypoint[12016]: WARNING: System::setSecurityManager has been called by org.opensearch.bootstrap.OpenSearch (file:/usr>
Nov 25 13:23:41 alma9.localdomain systemd-entrypoint[12016]: WARNING: Please consider reporting this to the maintainers of org.opensearch.bootstrap.OpenSearch
Nov 25 13:23:41 alma9.localdomain systemd-entrypoint[12016]: WARNING: System::setSecurityManager will be removed in a future release
Nov 25 13:23:42 alma9.localdomain systemd-entrypoint[12016]: Nov 25, 2024 1:23:42 PM sun.util.locale.provider.LocaleProviderAdapter <clinit>
Nov 25 13:23:42 alma9.localdomain systemd-entrypoint[12016]: WARNING: COMPAT locale provider will be removed in a future release
Nov 25 13:23:42 alma9.localdomain systemd-entrypoint[12016]: WARNING: A terminally deprecated method in java.lang.System has been called
Nov 25 13:23:42 alma9.localdomain systemd-entrypoint[12016]: WARNING: System::setSecurityManager has been called by org.opensearch.bootstrap.Security (file:/usr/s>
Nov 25 13:23:42 alma9.localdomain systemd-entrypoint[12016]: WARNING: Please consider reporting this to the maintainers of org.opensearch.bootstrap.Security
[root@alma9 wazuh-indexer]# 
```

**Comment by Orgoth** [comment]
Thank you very much for your time and affords.

Please forward this to the Team which is responsible for the documentation.
To prevent this from happening to other users.

Have a nice week.
